apiVersion: apps/v1
kind: Deployment
metadata:
  name: image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image
    spec:
      containers:
        - name: image
          image: wiljam/image:latest
          ports:
            - containerPort: 3001
      