apiVersion: apps/v1
kind: Deployment
metadata:
  name: images
spec:
  replicas: 1
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      containers:
        - name: images
          image: registry.cloud.cbh.kth.se/deploy-dac1887e-42b2-4716-abe1-fd266d22921d/images-wwnr
      