apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-images
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullstack-images
  template:
    metadata:
      labels:
        app: fullstack-images
    spec:
      containers:
      - name: fullstack-images
        image: wiljam/fullstack-images:latest
        ports:
        - containerPort: 3001
