apiVersion: v1
kind: Service
metadata:
  name: fullstack-images
spec:
  selector:
    app: fullstack-images
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 31623  # range 30000-32767
  type: NodePort
