name: kthcloud-ci
"on":
  push:
    branches:
    - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: '42e9ff7826313475c7d68ec451a31f4f0f53d5ee'
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: registry.cloud.cbh.kth.se
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.DOCKER_TAG }}
